### ISSUE TITLE
Alteração do nome do arquivo

### ISSUE THREAD

**Issue by rodrigo-reboucas** [razerageorge/Covid19-DataVisualization-Spark#1]
Parabéns pelo projeto, mas se colocar a extensão .ipynb no arquivo Engenharia e visualização de dados Covid19, a visualização será melhor.

**Comment by razerageorge** [comment]
Obrigado pela dica Rodrigo! Já atualizei o formato do arquivo, acabei mudando o nome já no Github e esqueci da extensão.
